### ISSUE TITLE
Support JDK 11

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#259]
WIP at https://github.com/uber/NullAway/tree/ms/jdk-11.  We should get the core NullAway functionality working first.  Some notes:

* I don't think coveralls works yet
* Android-related sample app building will be a pain
* [This JarInfer-related code](https://github.com/uber/NullAway/blob/ms/jdk-11/nullaway/src/main/java/com/uber/nullaway/handlers/InferredJARModelsHandler.java#L112) won't work on JDK 11; see [here](https://blog.codefx.org/java/java-11-migration-guide/#Casting-To-URL-Class-Loader).  We should probably disable this handler by default and enable via a flag anyway (along with a couple other rarely-used handlers).

**Comment by msridhar** [comment]
Another issue here: WALA seems to fail on JDK 11:

```
> Task :jar-infer:test-java-lib-jarinfer:jar FAILED
Exception in thread "main" java.lang.IllegalStateException: could not find boot classpath
        at com.ibm.wala.util.PlatformUtil.getBootClassPathJars(PlatformUtil.java:62)
        at com.ibm.wala.properties.WalaProperties.getJ2SEJarFiles(WalaProperties.java:64)
        at com.ibm.wala.util.config.AnalysisScopeReader.processScopeDefLine(AnalysisScopeReader.java:177)
        at com.ibm.wala.util.config.AnalysisScopeReader.read(AnalysisScopeReader.java:80)
        at com.ibm.wala.util.config.AnalysisScopeReader.readJavaScope(AnalysisScopeReader.java:53)
        at com.ibm.wala.util.config.AnalysisScopeReader.makePrimordialScope(AnalysisScopeReader.java:192)
        at com.uber.nullaway.jarinfer.DefinitelyDerefedParamsDriver.run(DefinitelyDerefedParamsDriver.java:160)
        at com.uber.nullaway.jarinfer.JarInfer.main(JarInfer.java:91)
```

**Comment by msridhar** [comment]
Did some digging here around what it would take to support running JarInfer on JDK 11.  There are two issues:

1. The WALA issue [from this comment](https://github.com/uber/NullAway/issues/259#issuecomment-443785457) is due to the fact that since JDK 9 the standard libraries are no longer distributed as jar files.  We can work around this by providing our own standard library jar (basically a stub jar for analysis); shouldn't be too hard.

2. The [code using URLClassLoader](https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/handlers/InferredJARModelsHandler.java#L112) is trickier to work around.  Here I think the best solution is to change JarInfer to rewrite library jars with nullability annotations, rather than generating stub files.  A shorter term solution would be to pass in the stubs as a separate argument to NullAway, rather than just including in the class path.  In either case, this will be more work to fix than 1.

FYI @lazaroclapp @kageiit

**Comment by kageiit** [comment]
I think code using UrlClassLoader is fine as we can just ignore classloaders which do not typecast safely. That said, the eventual plan is to rewrite jarinfer to embed stubs in jars along with bytecode instead of producing stub jars. We can probably have a switch to jarinfer to support both output jar/aar modes.

**Comment by msridhar** [comment]
@lazaroclapp thoughts here?

**Comment by lazaroclapp** [comment]
Basically, I agree that the long term solution is bytecode rewriting to add the annotations, which further buys us Kotlin support automatically.

As for the short term solutions, I see two options: add a check around that cast that will make that handler basically a no-op for Java 9 and above, or make code specific to Java 9+ to get the url out of a [BuiltinClassLoader](https://github.com/netroby/jdk9-dev/blob/master/jdk/src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java). The later seems doable by using reflection to access private fields (e.g. `LoadedModule.codeSourceURL`), but might need to be specialized per Java version supported 🤷‍♂️ . I'd be fine with either as a stopgap solution and can make the either change.

**Comment by msridhar** [comment]
Ok that makes sense. It might be better to crash with a relevant message rather than no-op. The JarInfer handler is off by default now, so users would only see the crash if they opted into JarInfer. Even better would be the workaround via reflection. I’m fine with only supporting JDK 11 but not intermediate releases since it’s a temporary fix.

**Comment by ctcpip** [comment]
current status?

**Comment by msridhar** [comment]
I think core NullAway should work fine on JDK 11.  It's lesser-used features like JarInfer that are still being worked on.  @lazaroclapp any other details?

**Comment by pwittchen** [comment]
Any news related with Java 11 support? Recently, I tried to integrate NullAway with a small Java 11 project built with Gradle and it didn't work. I received errors during the build, but I don't have logs now. I can try to reproduce this situation later.

**Comment by lazaroclapp** [comment]
Basic NullAway on Java 11 should work, we'd be happy to look at an issue here with a repo case.
