### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by dtomassi** [uber/NullAway#389]
Hi, I was running NullAway on a project and I encountered this error. Any thoughts?

I have included NullAway and Error Prone version along with the Stack Trace and code snippet. If anything else is needed, let me know! Thanks

NullAway Version:
0.7.9

Error Prone Version:
2.3.4

Stack Trace:
```
Adobe-Consulting-Services/acs-aem-commons/bundle/src/main/java/com/adobe/acs/commons/fam/impl/ActionManagerFactoryImpl.java:85: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
            stats.put(task.getStatistics());
                 ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.3.4
     BugPattern: NullAway
     Stack Trace:
     com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
  	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
  	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
  	at com.uber.nullaway.dataflow.DataFlow.dataflow(DataFlow.java:145)
  	at com.uber.nullaway.dataflow.DataFlow.resultFor(DataFlow.java:268)
  	at com.uber.nullaway.dataflow.DataFlow.resultForExpr(DataFlow.java:245)
  	at com.uber.nullaway.dataflow.DataFlow.expressionDataflow(DataFlow.java:190)
  	at com.uber.nullaway.dataflow.AccessPathNullnessAnalysis.getNullness(AccessPathNullnessAnalysis.java:92)
  	at com.uber.nullaway.NullAway.nullnessFromDataflow(NullAway.java:1987)
  	at com.uber.nullaway.NullAway.mayBeNullExpr(NullAway.java:1955)
  	at com.uber.nullaway.NullAway.matchDereference(NullAway.java:2037)
  	at com.uber.nullaway.NullAway.matchMemberSelect(NullAway.java:466)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:728)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2112)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:508)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:753)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1644)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:635)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1454)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:522)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.visitEnhancedForLoop(TreeScanner.java:306)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitEnhancedForLoop(ErrorProneScanner.java:622)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitEnhancedForLoop(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1166)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:522)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:742)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:550)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:562)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:152)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:56)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:952)
  	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:143)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:114)
  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:121)
  	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:68)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:884)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
  Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
  	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
  	at java.util.ArrayList.get(ArrayList.java:433)
  	at com.uber.nullaway.dataflow.AccessPathNullnessPropagation.setNullnessForMapCalls(AccessPathNullnessPropagation.java:899)
  	at com.uber.nullaway.dataflow.AccessPathNullnessPropagation.visitMethodInvocation(AccessPathNullnessPropagation.java:864)
  	at com.uber.nullaway.dataflow.AccessPathNullnessPropagation.visitMethodInvocation(AccessPathNullnessPropagation.java:138)
  	at shadow.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:76)
  	at shadow.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:408)
  	at shadow.checkerframework.dataflow.analysis.Analysis.performAnalysisBlock(Analysis.java:234)
  	at shadow.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:187)
  	at com.uber.nullaway.dataflow.DataFlow$1.load(DataFlow.java:87)
  	at com.uber.nullaway.dataflow.DataFlow$1.load(DataFlow.java:78)
  	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
  	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
  	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
  	... 130 more

```

Code Snippet:
Full link to [project/file](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a613fbc36f439eeaae9e3f0a387265191b318fb1/bundle/src/main/java/com/adobe/acs/commons/fam/impl/ActionManagerFactoryImpl.java#L85):
```
    @Override
    public TabularDataSupport getStatistics() throws OpenDataException {
        TabularDataSupport stats = new TabularDataSupport(ActionManagerImpl.getStaticsTableType());
        for (ActionManager task : tasks.values()) {
            stats.put(task.getStatistics());
        }
        return stats;
    }
```

**Comment by msridhar** [comment]
Thanks @dtomassi this definitely looks like a bug!  We will try to take a look soon.

**Comment by lazaroclapp** [comment]
Got it!

Here is what seems to be happening:

1. The class `TabularDataSupport` implements `java.util.Map<K,V>`
2. NullAway has special code to handle maps, and part of that code tries to detect all versions of `Map.put` (assuming the signature is `Foo.put(K k, V v)` where `Foo implements Map<K,V>` possibly transitively) 
3. NullAway detects these methods based on the method simple name and on the type implementing `Map`
4. `TabularDataSupport` does implement `Map`, and does override `put(K k, V v)` but it **also** adds `put(CompositeData value)` which NullAway doesn't know how to handle. That's the method being used in the snippet above.

I don't know what it would take to properly handle `put(CompositeData value)` in a general way (e.g. for types other than `TabularDataSupport` and `CompositeData`). If this is important to you, it might be worth it adding a [handler](https://github.com/uber/NullAway/wiki/How-NullAway-Works#extensibility-through-handlers) for those specific types.

That said, NullAway shouldn't crash on seeing this, it should just treat that single-argument `put(...)` as it would any other third-party method `bar(...)`. This is as easy as adding an argument number check to `isMapMethod` and it's helper methods [here](https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPath.java#L322). I'll try to do that later today.

**Comment by lazaroclapp** [comment]
This is fixed in master now. Will try to cut a new release with the fix later in the week.

**Comment by lazaroclapp** [comment]
Release 0.7.10, including this fix, has been sent to Maven Central and should propagate within the next day or so :)
