### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by marc-szalkiewicz-dd** [uber/NullAway#427]
Thank you for your great work on NullAway.

NullAway throws `java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.sun.source.tree.CaseTree.getStatements()" is null` when compiling a project that uses the [Immutables](https://immutables.github.io/) library.

Here is a small code snippet that shows the structure of the code where the NPE is thrown:

```
    public static SomeModel arbitrartyMethod(final SomeModel model) {
        final var foo = model.someMethod(); // NPE here
...
    // model.someMethod() is on a class annotated with @Value.Immutable
    @Value.Lazy
    default List<String> someMethod() {
        return someMethod().someField().stream().map(Field::name).collect(Collectors.toUnmodifiableList());
    }

```

Here are the versions used in the maven-compiler-plugin `annotationProcessorPaths`:

```
<path>
    <groupId>com.google.errorprone</groupId>
    <artifactId>error_prone_core</artifactId>
    <version>2.4.0</version>
</path>
<path>
    <groupId>com.uber.nullaway</groupId>
    <artifactId>nullaway</artifactId>
    <version>0.8.0</version>
</path>
```

Here is the full stack trace:

```
Compilation failure
[ERROR] SomeFile.java:[108,43] error: An unhandled exception was thrown by the Error Prone static analysis plugin.
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.4.0
[ERROR]      BugPattern: NullAway
[ERROR]      Stack Trace:
[ERROR]      com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.sun.source.tree.CaseTree.getStatements()" is null
[ERROR]   	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
[ERROR]   	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
[ERROR]   	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[ERROR]   	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
[ERROR]   	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
[ERROR]   	at com.uber.nullaway.dataflow.DataFlow.dataflow(DataFlow.java:142)
[ERROR]   	at com.uber.nullaway.dataflow.DataFlow.resultFor(DataFlow.java:272)
[ERROR]   	at com.uber.nullaway.dataflow.DataFlow.resultForExpr(DataFlow.java:249)
[ERROR]   	at com.uber.nullaway.dataflow.DataFlow.expressionDataflow(DataFlow.java:192)
[ERROR]   	at com.uber.nullaway.dataflow.AccessPathNullnessAnalysis.getNullness(AccessPathNullnessAnalysis.java:96)
[ERROR]   	at com.uber.nullaway.NullAway.nullnessFromDataflow(NullAway.java:1966)
[ERROR]   	at com.uber.nullaway.NullAway.mayBeNullExpr(NullAway.java:1934)
[ERROR]   	at com.uber.nullaway.NullAway.matchDereference(NullAway.java:2016)
[ERROR]   	at com.uber.nullaway.NullAway.matchMemberSelect(NullAway.java:441)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:728)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2293)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:527)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:753)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1761)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:225)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:887)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1001)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:250)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:522)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1059)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:208)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:742)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:925)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:189)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:550)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:832)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:562)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:603)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[ERROR]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1421)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1368)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:59)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:45)
[ERROR]   Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.sun.source.tree.CaseTree.getStatements()" is null
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne$SwitchBuilder.buildCase(CFGBuilder.java:3374)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne$SwitchBuilder.build(CFGBuilder.java:3347)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitSwitch(CFGBuilder.java:3285)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitSwitch(CFGBuilder.java:1416)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1256)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3261)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1416)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1059)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitEnhancedForLoop(CFGBuilder.java:3650)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitEnhancedForLoop(CFGBuilder.java:1416)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1199)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3261)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1416)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1059)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1571)
[ERROR]   	at shadow.checkerframework.dataflow.cfg.CFGBuilder.build(CFGBuilder.java:255)
[ERROR]   	at com.uber.nullaway.dataflow.DataFlow$2.load(DataFlow.java:126)
[ERROR]   	at com.uber.nullaway.dataflow.DataFlow$2.load(DataFlow.java:96)
[ERROR]   	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
[ERROR]   	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
[ERROR]   	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
[ERROR]   	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
[ERROR]   	... 80 more
```

**Comment by lazaroclapp** [comment]
Hi @marc-szalkiewicz-dd, at a glance, and after taking a look at `org.immutables`, this looks very similar to the EP/Lombok compatibility issues, where one tool modifies the AST in memory during compilation, confusing the other which doesn't expect the transformed code.

It's hard to understand what's going on without the transformed source in hand. That is: the code after that `@Value.Lazy` annotation is processed, which will include the `com.sun.source.tree.CaseTree` about which the NullAway stack trace is complaining (you'll notice the original code has no `case x:` statements, but the transformed code probably does). 

We can try our hand at building a repro project that sets up both the `org.immutables` annotation processor and NullAway in Gradle, then debug from there. That said, if you could provide such repro project, then we might be able to look at it a bit faster 🙂
